<?php

namespace App\Enums;

enum Currency: int
{
    case AED = 1;
    case AFN = 2;
    case ALL = 3;
    case AMD = 4;
    case ANG = 5;
    case AOA = 6;
    case ARS = 7;
    case AUD = 8;
    case AWG = 9;
    case AZN = 10;
    case BAM = 11;
    case BBD = 12;
    case BDT = 13;
    case BGN = 14;
    case BHD = 15;
    case BIF = 16;
    case BMD = 17;
    case BND = 18;
    case BOB = 19;
    case BRL = 20;
    case BSD = 21;
    case BTN = 22;
    case BWP = 23;
    case BYR = 24;
    case BZD = 25;
    case CAD = 26;
    case CDF = 27;
    case CHF = 28;
    case CLP = 29;
    case CNY = 30;
    case COP = 31;
    case CRC = 32;
    case CUP = 33;
    case CVE = 34;
    case CYP = 35;
    case CZK = 36;
    case DJF = 37;
    case DKK = 38;
    case DOP = 39;
    case DZD = 40;
    case EEK = 41;
    case EGP = 42;
    case ERN = 43;
    case ETB = 44;
    case EUR = 45;
    case FJD = 46;
    case FKP = 47;
    case GBP = 48;
    case GEL = 49;
    case GHS = 50;
    case GIP = 51;
    case GMD = 52;
    case GNF = 53;
    case GTQ = 54;
    case GYD = 55;
    case HKD = 56;
    case HNL = 57;
    case HRK = 58;
    case HTG = 59;
    case HUF = 60;
    case IDR = 61;
    case ILS = 62;
    case INR = 63;
    case IQD = 64;
    case IRR = 65;
    case ISK = 66;
    case JMD = 67;
    case JOD = 68;
    case JPY = 69;
    case KES = 70;
    case KGS = 71;
    case KHR = 72;
    case KMF = 73;
    case KPW = 74;
    case KRW = 75;
    case KWD = 76;
    case KYD = 77;
    case KZT = 78;
    case LAK = 79;
    case LBP = 80;
    case LKR = 81;
    case LRD = 82;
    case LSL = 83;
    case LTL = 84;
    case LVL = 85;
    case LYD = 86;
    case MAD = 87;
    case MDL = 88;
    case MGA = 89;
    case MKD = 90;
    case MMK = 91;
    case MNT = 92;
    case MOP = 93;
    case MRO = 94;
    case MTL = 95;
    case MUR = 96;
    case MVR = 97;
    case MWK = 98;
    case MXN = 99;
    case MYR = 100;
    case MZN = 101;
    case NAD = 102;
    case NGN = 103;
    case NIO = 104;
    case NOK = 105;
    case NPR = 106;
    case NZD = 107;
    case OMR = 108;
    case PAB = 109;
    case PEN = 110;
    case PGK = 111;
    case PHP = 112;
    case PKR = 113;
    case PLN = 114;
    case PYG = 115;
    case QAR = 116;
    case RON = 117;
    case RSD = 118;
    case RUB = 119;
    case RWF = 120;
    case SAR = 121;
    case SBD = 122;
    case SCR = 123;
    case SDG = 124;
    case SEK = 125;
    case SGD = 126;
    case SHP = 127;
    case SKK = 128;
    case SLL = 129;
    case SOS = 130;
    case SRD = 131;
    case SSP = 132;
    case STD = 133;
    case SVC = 134;
    case SYP = 135;
    case SZL = 136;
    case THB = 137;
    case TJS = 138;
    case TMT = 139;
    case TND = 140;
    case TOP = 141;
    case TRY = 142;
    case TTD = 143;
    case TWD = 144;
    case TZS = 145;
    case UAH = 146;
    case UGX = 147;
    case USD = 148;
    case UYU = 149;
    case UZS = 150;
    case VEF = 151;
    case VES = 152;
    case VND = 153;
    case VUV = 154;
    case WST = 155;
    case XAF = 156;
    case XCD = 157;
    case XOF = 158;
    case XPF = 159;
    case YER = 160;
    case ZAR = 161;
    case ZMW = 162;
    case ZWD = 163;
    case ZWL = 164;

    /**
     * The number of decimals this currency supports.
     */
    public function decimals(): int
    {
        return match ($this) {
            self::BHD => 3,
            self::BIF => 0,
            self::CLP => 0,
            self::DJF => 0,
            self::GNF => 0,
            self::IQD => 3,
            self::ISK => 0,
            self::JOD => 3,
            self::JPY => 0,
            self::KMF => 0,
            self::KRW => 0,
            self::KWD => 3,
            self::LYD => 3,
            self::OMR => 3,
            self::PYG => 0,
            self::RWF => 0,
            self::TND => 3,
            self::UGX => 0,
            self::VND => 0,
            self::VUV => 0,
            self::XAF => 0,
            self::XOF => 0,
            self::XPF => 0,
            default => 2,
        };
    }

    public function symbol(): ?string
    {
        return match ($this) {
            self::AED => 'AED',
            self::AFN => '؋',
            self::ALL => 'Lek',
            self::AMD => 'AMD',
            self::ANG => 'ƒ',
            self::AOA => 'Kz',
            self::ARS => '$',
            self::AUD => '$',
            self::AWG => 'ƒ',
            self::AZN => 'ман',
            self::BAM => 'KM',
            self::BBD => '$',
            self::BDT => 'BDT',
            self::BGN => 'лв',
            self::BHD => 'BHD',
            self::BIF => 'BIF',
            self::BMD => '$',
            self::BND => '$',
            self::BOB => '$b',
            self::BRL => 'R$',
            self::BSD => '$',
            self::BTN => 'BTN',
            self::BWP => 'P',
            self::BYR => 'p.',
            self::BZD => 'BZ$',
            self::CAD => '$',
            self::CDF => 'CDF',
            self::CHF => 'CHF',
            self::CLP => 'CLP',
            self::CNY => '¥',
            self::COP => '$',
            self::CRC => '₡',
            self::CUP => '₱',
            self::CVE => 'CVE',
            self::CYP => 'CYP',
            self::CZK => 'Kč',
            self::DJF => 'DJF',
            self::DKK => 'kr',
            self::DOP => 'RD$',
            self::DZD => 'DZD',
            self::EEK => 'kr',
            self::EGP => '£',
            self::ERN => 'Nfk',
            self::ETB => 'ETB',
            self::EUR => '€',
            self::FJD => '$',
            self::FKP => '£',
            self::GBP => '£',
            self::GEL => 'GEL',
            self::GHS => '¢',
            self::GIP => '£',
            self::GMD => 'D',
            self::GNF => 'GNF',
            self::GTQ => 'Q',
            self::GYD => '$',
            self::HKD => '$',
            self::HNL => 'L',
            self::HRK => 'kn',
            self::HTG => 'G',
            self::HUF => 'Ft',
            self::IDR => 'Rp',
            self::ILS => '₪',
            self::INR => '₹',
            self::IQD => 'IQD',
            self::IRR => '﷼',
            self::ISK => 'kr',
            self::JMD => '$',
            self::JOD => 'JOD',
            self::JPY => '¥',
            self::KES => 'KES',
            self::KGS => 'лв',
            self::KHR => '៛',
            self::KMF => 'KMF',
            self::KPW => '₩',
            self::KRW => '₩',
            self::KWD => 'KWD',
            self::KYD => '$',
            self::KZT => 'лв',
            self::LAK => '₭',
            self::LBP => '£',
            self::LKR => '₨',
            self::LRD => '$',
            self::LSL => 'L',
            self::LTL => 'Lt',
            self::LVL => 'Ls',
            self::LYD => 'LYD',
            self::MAD => 'MAD',
            self::MDL => 'MDL',
            self::MGA => 'MGA',
            self::MKD => 'ден',
            self::MMK => 'K',
            self::MNT => '₮',
            self::MOP => 'MOP',
            self::MRO => 'UM',
            self::MTL => 'MTL',
            self::MUR => '₨',
            self::MVR => 'Rf',
            self::MWK => 'MK',
            self::MXN => '$',
            self::MYR => 'RM',
            self::MZN => 'MT',
            self::NAD => '$',
            self::NGN => '₦',
            self::NIO => 'C$',
            self::NOK => 'kr',
            self::NPR => '₨',
            self::NZD => '$',
            self::OMR => '﷼',
            self::PAB => 'B/.',
            self::PEN => 'S/.',
            self::PGK => 'PGK',
            self::PHP => 'Php',
            self::PKR => '₨',
            self::PLN => 'zł',
            self::PYG => 'Gs',
            self::QAR => '﷼',
            self::RON => 'lei',
            self::RSD => 'Дин',
            self::RUB => 'руб',
            self::RWF => 'RWF',
            self::SAR => 'SAR',
            self::SBD => '$',
            self::SCR => '₨',
            self::SDG => 'ج.س.',
            self::SEK => 'kr',
            self::SGD => '$',
            self::SHP => '£',
            self::SKK => 'Sk',
            self::SLL => 'Le',
            self::SOS => 'S',
            self::SRD => '$',
            self::SSP => 'SSP',
            self::STD => 'Db',
            self::SVC => '$',
            self::SYP => '£',
            self::SZL => 'SZL',
            self::THB => '฿',
            self::TJS => 'TJS',
            self::TMT => 'T',
            self::TND => 'TND',
            self::TOP => 'T$',
            self::TRY => 'YTL',
            self::TTD => 'TT$',
            self::TWD => 'NT$',
            self::TZS => 'TZS',
            self::UAH => '₴',
            self::UGX => 'UGX',
            self::USD => '$',
            self::UYU => '$U',
            self::UZS => 'лв',
            self::VEF => 'Bs',
            self::VES => 'Bs.',
            self::VND => '₫',
            self::VUV => 'Vt',
            self::WST => 'WS$',
            self::XAF => 'FCF',
            self::XCD => '$',
            self::XOF => 'XOF',
            self::XPF => 'XPF',
            self::YER => '﷼',
            self::ZAR => 'R',
            self::ZMW => 'ZK',
            self::ZWD => 'Z$',
            self::ZWL => '$',
            default => null,
        };
    }
}
